---
applications:
  - name: tax-servicing-loan-boarding-rules-api-{target}
    memory: 2G
    instances: 2
    path: ../build/libs/tax-servicing-loan-boarding-rules-api-1.0.RELEASE.jar
    buildpack: java_buildpack_offline
    timeout: 180
    routes:
      - route: tax-servicing-loan-boarding-rules-api-{env-target}.apps.pcfwtcprd.clgxlabs.io
    env:
      SPRING_PROFILES_ACTIVE: ext-uat
      JAVA_OPTS: -XX:MaxMetaspaceSize=384M
#      JBP_CONFIG_APP_DYNAMICS_AGENT: '{default_application_name: "uat:tax-payment-decisions", default_tier_name: "tpd-rules"}'

    services:
      - config-server
      - config-server-keystore
      - logstash-syslog
      - elastic-apm

